export default defineAppConfig({
  shadcnDocs: {
    site: {
      name: 'بیت نت مارکت',
      description: 'Beautifully designed Nuxt Content template built with shadcn-vue. Customizable. Compatible. Open Source.',
      ogImage: '/hero.png',
    },
    theme: {
      customizable: true,
      color: 'yellow',
      radius: 0.5,
      direction: 'rtl',
    },
    header: {
      title: 'Bitnetmarket',
      showTitle: false,
      border: false,
      icon: {
        light: '/bitnetmarket_icon1.svg',
        dark: '/bitnetmarket_icon1.svg',
      },
      showIcon: true,
      logo: {
        light: '/bitnetmarket_logo.svg',
        dark: '/bitnetmarket_logo_dark.svg',
      },
      showTitleInMobile: true,
      darkModeToggle: true,
      nav: [{
        title: 'مستندات',
        links: [{
          title: 'فروشنده',
          to: '/seller',
          description: 'مطالب مربوط به فروشندگان',
        }, {
          title: 'مشتری',
          to: '/customer',
          description: 'مطالب مربوط به مشتریان',
          target: '_self',
        }],
      }, {
        title: 'مارکت',
        to: 'https://www.bitnetmarket.com/',
        target: '_blank',
      }],
      links: [{
        icon: 'lucide:github',
        to: 'https://github.com/znxn7717/shadcn',
        target: '_blank',
      }],
    },
    aside: {
      useLevel: true,
      collapse: false,
    },
    main: {
      breadCrumb: false,
      showTitle: false,
      codeCopyToast: true,
      codeIcon: {
        'package.json': 'vscode-icons:file-type-node',
        'tsconfig.json': 'vscode-icons:file-type-tsconfig',
        '.npmrc': 'vscode-icons:file-type-npm',
        '.editorconfig': 'vscode-icons:file-type-editorconfig',
        '.eslintrc': 'vscode-icons:file-type-eslint',
        '.eslintrc.cjs': 'vscode-icons:file-type-eslint',
        '.eslintignore': 'vscode-icons:file-type-eslint',
        'eslint.config.js': 'vscode-icons:file-type-eslint',
        'eslint.config.mjs': 'vscode-icons:file-type-eslint',
        'eslint.config.cjs': 'vscode-icons:file-type-eslint',
        '.gitignore': 'vscode-icons:file-type-git',
        'yarn.lock': 'vscode-icons:file-type-yarn',
        '.env': 'vscode-icons:file-type-dotenv',
        '.env.example': 'vscode-icons:file-type-dotenv',
        '.vscode/settings.json': 'vscode-icons:file-type-vscode',
        'nuxt': 'vscode-icons:file-type-nuxt',
        '.nuxtrc': 'vscode-icons:file-type-nuxt',
        '.nuxtignore': 'vscode-icons:file-type-nuxt',
        'nuxt.config.js': 'vscode-icons:file-type-nuxt',
        'nuxt.config.ts': 'vscode-icons:file-type-nuxt',
        'nuxt.schema.ts': 'vscode-icons:file-type-nuxt',
        'tailwind.config.js': 'vscode-icons:file-type-tailwind',
        'tailwind.config.ts': 'vscode-icons:file-type-tailwind',
        'vue': 'vscode-icons:file-type-vue',
        'ts': 'vscode-icons:file-type-typescript',
        'tsx': 'vscode-icons:file-type-typescript',
        'mjs': 'vscode-icons:file-type-js',
        'cjs': 'vscode-icons:file-type-js',
        'js': 'vscode-icons:file-type-js',
        'jsx': 'vscode-icons:file-type-js',
        'md': 'vscode-icons:file-type-markdown',
        'mdc': 'vscode-icons:file-type-markdown',
        'py': 'vscode-icons:file-type-python',
        'npm': 'vscode-icons:file-type-npm',
        'pnpm': 'vscode-icons:file-type-pnpm',
        'npx': 'vscode-icons:file-type-npm',
        'yarn': 'vscode-icons:file-type-yarn',
        'bun': 'vscode-icons:file-type-bun',
        'yml': 'vscode-icons:file-type-yaml',
        'json': 'vscode-icons:file-type-json',
        'terminal': 'lucide:terminal',
      },
    },
    footer: {
      credits: 'MIT سورس باز',
      links: [
        {
          title: 'بیت نت مارکت',
          to: 'https://www.bitnetmarket.com/',
          target: '_blank',
        },
        {
          icon: 'lucide:github',
          to: 'https://github.com/znxn7717/shadcn',
          target: '_blank',
        },
      ],
    },
    toc: {
      enable: true,
      title: 'عناوین این صفحه',
      links: [{
        title: 'امتیاز گیت هاب',
        icon: 'lucide:star',
        to: 'https://github.com/znxn7717/shadcn',
        target: '_blank',
      }, {
        title: 'پنل فروشنده',
        icon: 'lucide:circle-dot',
        to: 'https://seller.bitnetmarket.com',
        target: '_blank',
      }],
    },
    search: {
      enable: true,
      inAside: false,
    },
  },
});
