services:
  help_frontend:
    build: .
    image: help_frontend
    container_name: help_frontend
    ports:
      - "3002:3000"
    # volumes:
    #   - .:/app # برای توسعه، تغییرات را سینک می‌کند
    networks:
      - 1panel-network
    restart: unless-stopped

networks:
  1panel-network:
    external: true